#!/bin/sh
set -eu
server=${SPECK_SERVER:-https://speckrmm.com}
[ "$(id -u)" = 0 ] || { echo 'Run as root.' >&2; exit 1; }
case "$server" in https://*) ;; *) echo 'An HTTPS server is required.' >&2; exit 1;; esac
case "$(uname -m)" in x86_64) arch=amd64;; aarch64) arch=arm64;; *) echo 'Unsupported CPU architecture' >&2; exit 1;; esac
command -v curl >/dev/null || { echo 'Install curl first.' >&2; exit 1; }
install -d -m 700 /etc/speck
binary="speck-agent-linux-$arch"
tasktmp=$(mktemp -d)
trap 'rm -rf "$tasktmp"' EXIT INT TERM
curl --fail --silent --show-error "$server/downloads/$binary" -o "$tasktmp/$binary"
curl --fail --silent --show-error "$server/downloads/SHA256SUMS" -o "$tasktmp/SHA256SUMS"
(cd "$tasktmp" && awk -v b="$binary" '$2==b' SHA256SUMS > selected && test -s selected && sha256sum -c selected)
if systemctl is-active --quiet SpeckAgent; then systemctl stop SpeckAgent; fi
install -m 755 "$tasktmp/$binary" /usr/local/bin/speck-agent
if [ ! -f /etc/speck/agent.json ]; then
 if [ -z "${SPECK_ENROLLMENT_TOKEN:-}" ]; then
  printf 'Single-use enrollment token: '
  stty -echo; read -r SPECK_ENROLLMENT_TOKEN; stty echo; printf '\n'
 fi
 # Tokens generated by Speck contain only URL-safe base64 characters.
 case "$SPECK_ENROLLMENT_TOKEN" in *[!a-zA-Z0-9_-]*) echo 'Invalid token' >&2; exit 1;; esac
 printf '{"server":"%s","token":"%s"}\n' "$server" "$SPECK_ENROLLMENT_TOKEN" | /usr/local/bin/speck-agent enroll
 unset SPECK_ENROLLMENT_TOKEN
fi
if [ ! -f /etc/systemd/system/SpeckAgent.service ]; then /usr/local/bin/speck-agent install; fi
# Desktop helper is unprivileged. Headless machines do not launch it.
chmod 711 /etc/speck
install -d -m 1777 /etc/speck/telemetry
install -d -m 755 /etc/xdg/autostart
cat > /etc/xdg/autostart/speck-foreground.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=Speck active application reporter
Exec=/usr/local/bin/speck-agent foreground
Terminal=false
EOF
systemctl daemon-reload
systemctl enable --now SpeckAgent
echo 'Speck installed. Active-app reporting requires an X11 desktop sign-in and xprop.'
