// Code generated by scripts/brand.mjs; DO NOT EDIT.
package identity

const Name = "Speck"
const Tagline = "A LITTLE LIGHTWEIGHT RMM"
const Agent = "Speck Agent"
const Desktop = "Speck Desktop Helper"
const Description = "Windows and Linux monitoring, remote access and recovery."
