// Rebuild shared brand assets. Run after npm --prefix web ci.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
const root = path.resolve(import.meta.dirname, "..");
const require = createRequire(path.join(root, "web/package.json"));
const { Resvg } = require("@resvg/resvg-js");
const brand = JSON.parse(
  fs.readFileSync(path.join(root, "brand/identity.json"), "utf8"),
);
const c = brand.colors;
const dir = path.join(root, "brand/assets");
fs.mkdirSync(dir, { recursive: true });
const write = (name, data) => fs.writeFileSync(path.join(dir, name), data);
const rays =
  Array.from(
    { length: 8 },
    (_, i) =>
      `<rect x="29" y="4" width="6" height="19" rx="3" transform="rotate(${i * 45} 32 32)"/>`,
  ).join("") + '<circle cx="32" cy="32" r="3"/>';
const mark = (color) => `<g fill="${color}">${rays}</g>`;
const svg = (width, height, body) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}">${body}</svg>\n`;
const outline = fs.readFileSync(
  path.join(root, "brand/wordmark-path.svg"),
  "utf8",
);
const lettering = outline.match(/<path[^>]+\/>/)[0];
const wordWidth = Number(outline.match(/viewBox="0 0 ([\d.]+) 80"/)[1]);
for (const [variant, color] of [
  ["forest", c.forest],
  ["lime", c.lime],
  ["white", c.white],
  ["black", "#000000"],
]) {
  write(`speck-mark-${variant}.svg`, svg(64, 64, mark(color)));
  write(
    `speck-wordmark-${variant}.svg`,
    svg(
      wordWidth + 84,
      80,
      `<g transform="translate(0 8)">${mark(color)}</g><g fill="${color}" transform="translate(84 0)">${lettering}</g>`,
    ),
  );
}
const tile = svg(
  64,
  64,
  `<rect width="64" height="64" rx="14" fill="${c.forest}"/><g transform="translate(8 8) scale(.75)">${mark(c.lime)}</g>`,
);
write("speck-icon.svg", tile);
const sizes = [16, 24, 32, 48, 64, 128, 256];
const pngs = sizes.map((size) =>
  new Resvg(tile, { fitTo: { mode: "width", value: size } }).render().asPng(),
);
for (let i = 0; i < sizes.length; i++)
  write(`speck-icon-${sizes[i]}.png`, pngs[i]);
const ico = Buffer.alloc(6 + 16 * sizes.length);
ico.writeUInt16LE(1, 2);
ico.writeUInt16LE(sizes.length, 4);
let offset = ico.length;
for (let i = 0; i < sizes.length; i++) {
  const pos = 6 + 16 * i;
  ico[pos] = ico[pos + 1] = sizes[i] % 256;
  ico.writeUInt16LE(1, pos + 4);
  ico.writeUInt16LE(32, pos + 6);
  ico.writeUInt32LE(pngs[i].length, pos + 8);
  ico.writeUInt32LE(offset, pos + 12);
  offset += pngs[i].length;
}
write("speck.ico", Buffer.concat([ico, ...pngs]));
write(
  "speck-apple-touch.png",
  new Resvg(tile, { fitTo: { mode: "width", value: 180 } }).render().asPng(),
);
const vars = Object.entries(c)
  .map(([key, v]) => `  --${key}: ${v};`)
  .join("\n");
fs.writeFileSync(
  path.join(root, "brand/tokens.css"),
  `/* Generated from brand/identity.json by scripts/brand.mjs. */\n:root {\n${vars}\n  --green: var(--fern);\n  --radius: 10px;\n  --space: 4px;\n}\n`,
);
const publicDir = path.join(root, "web/public/assets/brand");
fs.mkdirSync(publicDir, { recursive: true });
for (const name of fs.readdirSync(dir))
  fs.copyFileSync(path.join(dir, name), path.join(publicDir, name));
fs.copyFileSync(
  path.join(root, "brand/fonts/InterVariable.woff2"),
  path.join(publicDir, "InterVariable.woff2"),
);
fs.copyFileSync(
  path.join(root, "brand/fonts/OFL.txt"),
  path.join(publicDir, "OFL.txt"),
);
for (const [command, description] of [
  ["speck-agent", "Speck Agent"],
  ["speck-desktop", "Speck Desktop Helper"],
]) {
  const resource = {
    RT_GROUP_ICON: { APP: { "0000": "../assets/speck.ico" } },
    RT_VERSION: {
      "#1": {
        "0409": {
          fixed: { file_version: "0.1.0.0", product_version: "0.1.0.0" },
          info: {
            "0409": {
              CompanyName: "Speck contributors",
              FileDescription: description,
              ProductName: "Speck RMM",
              ProductVersion: "0.1.0",
              FileVersion: "0.1.0",
              OriginalFilename: command + ".exe",
              InternalName: command,
              Comments: brand.tagline,
              LegalCopyright: "Copyright Speck contributors. MIT licensed.",
            },
          },
        },
      },
    },
  };
  const resDir = path.join(root, "brand/windows");
  fs.mkdirSync(resDir, { recursive: true });
  fs.writeFileSync(
    path.join(resDir, command + ".json"),
    JSON.stringify(resource, null, 2) + "\n",
  );
}
const identityDir = path.join(root, "agent/internal/identity");
fs.mkdirSync(identityDir, { recursive: true });
fs.writeFileSync(
  path.join(identityDir, "brand.go"),
  `// Code generated by scripts/brand.mjs; DO NOT EDIT.\npackage identity\n\nconst Name = ${JSON.stringify(brand.name)}\nconst Tagline = ${JSON.stringify(brand.tagline)}\nconst Agent = \"Speck Agent\"\nconst Desktop = \"Speck Desktop Helper\"\nconst Description = \"Windows and Linux monitoring, remote access and recovery.\"\n`,
);
console.log(
  "Speck brand assets built: SVG, PNG, ICO, tokens and Windows metadata.",
);
